language: scala

jdk:
- oraclejdk8

scala:
- 2.12.3

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_4e09b178a370_key -iv $encrypted_4e09b178a370_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI

after_success:
- bash <(curl -s https://codecov.io/bash) -t 5b75b318-ab71-4fbc-9203-bfa7765cdbdc
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
